### ISSUE TITLE
/_public routes and /enhance-styles.css respond with 404

### ISSUE THREAD

**Issue by sykesd** [enhance-dev/fastify-plugin#5]
I started with the Enhance [quick start](https://enhance.dev/docs/) project. This works exactly as documented.

Following the [Fastify docs](https://enhance.dev/docs/learn/deployment/fastify), I then did the following in my quick start project:

- added the dependencies `yarn add fastify @enhance/fastify-plugin`
- added the script `"node index.mjs"` to my `package.json`
- added the `index.mjs` to the root folder of my project, exactly as described in the docs

The contents of `index.mjs` are:
```javascript
import Fastify from 'fastify'
import Enhance from '@enhance/fastify-plugin'

const app = Fastify()

app.register(Enhance)

app.listen({ port: 3000 }, console.log)
```

When I launch this, the console shows:
```
null http://127.0.0.1:3000
```

When I visit http://localhost:3000 I see the expected content, but without styling or any images. When I check the developer tools I see that all requests for static content via /_public as well as the request for the CSS /enhance-styles.css all respond with 404.

This is on Windows 10 x64 on node 18.14.2.

I am assuming this is configuration, but I know so little about this that I don't know where to start.

NOTE: I am considering this for internal applications that would be running on internal infrastructure. Deploying to any cloud provider is not an option.

**Comment by kristoferjoseph** [comment]
Yes, the starter project works as expected but it isn’t designed to be used with the fastify plugin. All the routes are preconfigured to work with AWS Lambda. To replicate the starter project behavior with fastify you would need to configure the public folder and update static asset urls. 

The fastify plugin is a roll your own solution so you would want to start with something more like this example:
https://github.com/brianleroux/enhance-ssr-standalone

**Comment by kristoferjoseph** [comment]
Looks like static assets need to be configured. 

The public folder needs to be mounted and the URLs to static assets would need to be updated. 

https://github.com/fastify/fastify-static

**Comment by kristoferjoseph** [comment]
These instructions are how the plugin is meant to be used:
https://enhance.dev/docs/learn/deployment/fastify

This plugin was designed to be used as such and not added to the enhance starter project.
